#!/usr/bin/env python3
"""
Hybrid static builder for Chemical Enlightenment.

For each page it does TWO things:
  1. Prerenders a real dist/<slug>.html with the full content baked in
     (works with no JavaScript -> SEO + accessibility friendly).
  2. Emits dist/js/content.js (window.SITE) so static/js/app.js can swap
     content client-side via the History API for instant SPA-style navigation.

Usage:  python build.py
"""
import os
import json
import shutil
import datetime
import markdown
import jinja2

ROOT = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.join(ROOT, "content")
TEMPLATES = os.path.join(ROOT, "templates")
STATIC = os.path.join(ROOT, "static")
DIST = os.path.join(ROOT, "dist")

ORDER = ["index", "general-chemistry", "ap-chemistry",
         "ap-chemistry-sub-page-unit-topics", "ap-chemistry-sub-page-lab-techniques",
         "ap-chemistry-sub-page-practice-exams", "science-olympiad",
         "scioly-sub-page-current-season-topics", "scioly-sub-page-tips-for-competition",
         "scioly-sub-page-practice-tests"]


def active_for(slug):
    if slug == "index":
        return "index"
    if slug.startswith("ap-chemistry"):
        return "ap-chemistry"
    if slug.startswith("science-olympiad") or slug.startswith("scioly"):
        return "science-olympiad"
    if slug.startswith("general-chemistry"):
        return "general-chemistry"
    return ""


def parse_front_matter(text):
    meta = {}
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) == 3:
            for line in parts[1].strip().splitlines():
                k, _, v = line.partition(":")
                meta[k.strip()] = v.strip().strip('"')
            return meta, parts[2].lstrip("\n")
    return meta, text


def clean_dist():
    if os.path.isdir(DIST):
        shutil.rmtree(DIST)
    os.makedirs(DIST)
    for sub in ("css", "img", "js"):
        src = os.path.join(STATIC, sub)
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(DIST, sub))
    os.makedirs(os.path.join(DIST, "js"), exist_ok=True)
    open(os.path.join(DIST, ".nojekyll"), "w").close()


def main():
    clean_dist()
    md = markdown.Markdown(extensions=["extra", "sane_lists", "attr_list"])

    # Pass 1: collect rendered page data (single source for both outputs).
    pages = {}
    for fname in os.listdir(CONTENT):
        if not fname.endswith(".md"):
            continue
        meta, body = parse_front_matter(open(os.path.join(CONTENT, fname), encoding="utf-8").read())
        slug = meta.get("slug") or os.path.splitext(fname)[0]
        html = md.convert(body)
        md.reset()
        pages[slug] = {"title": meta.get("title", slug),
                       "description": meta.get("description", ""),
                       "html": html}

    order = [s for s in ORDER if s in pages] + [s for s in pages if s not in ORDER]

    # content.js for client-side hydration / navigation.
    data = {"pages": pages, "order": order,
            "nav": [["index", "Home"], ["ap-chemistry", "AP Chemistry"],
                    ["science-olympiad", "Science Olympiad"], ["general-chemistry", "General Chemistry"]]}
    with open(os.path.join(DIST, "js", "content.js"), "w", encoding="utf-8") as f:
        f.write("/* Generated by build.py — do not edit by hand. */\n")
        f.write("window.SITE = " + json.dumps(data, ensure_ascii=False) + ";\n")

    # Pass 2: prerender a real HTML file per route (content baked in).
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(TEMPLATES),
                             autoescape=False, undefined=jinja2.StrictUndefined)
    template = env.get_template("base.html")
    year = datetime.date.today().year
    for slug in order:
        p = pages[slug]
        out = template.render(title=p["title"], description=p["description"],
                              content=p["html"], active=active_for(slug), year=year)
        open(os.path.join(DIST, slug + ".html"), "w", encoding="utf-8").write(out)

    print(f"Prerendered {len(order)} pages + content.js -> {DIST}")
    for slug in order:
        print("  ", slug + ".html")


if __name__ == "__main__":
    main()
